---
version: "3.7"

services:

  throttling-proxy:
    build:
      context: ./throttling-proxy/
      dockerfile: Dockerfile
    image: local/throttling-proxy
    container_name: throttling-proxy
    restart: on-failure
    environment:
      UPSTREAM: ookla:8080
      # The limitation of the bandwidth in byes.
      # Using units is possible (4k, 2M, ...). Default is 0 (no limit).
      LIMIT: 512k
      # The number of seconds to delay the response. Default is 0.0.
      DELAY: 0.25
      RESOLVER: 127.0.0.11
    ports:
    - 0.0.0.0:8080:8080

  ookla:
    build:
      context: ./ookla/
      dockerfile: Dockerfile
    image: local/ookla
    container_name: ookla
    restart: on-failure
    ports:
    - 0.0.0.0:8081:8080
