name: go-cd

on:
  workflow_run:
    workflows: ["go-ci"]
    branches: [main]
    types:
      - completed

jobs:
  # setup:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: set up
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: ^1.16
  #       id: go
  #     - name: check out
  #       uses: actions/checkout@v2
  #     - name: Cache
  #       uses: actions/cache@v2.1.0
  #       with:
  #         path: ~/go/pkg/mod
  #         key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
  #         restore-keys: |
  #           ${{ runner.os }}-go-

  release:
    # needs: setup
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: build & push docker image
        run: make docker-push
