name: go-cd

on:
  workflow_run:
    workflows: ["go-ci"]
    branches: [main]
    types:
      - completed

jobs:
  release:
    # needs: setup
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: build & push docker image
        run: make docker-push
